### ISSUE TITLE
Verify release one last time

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-developmental-ontology#4]
@Clare72 I finished the full fbdv release. Compare

https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbdv/releases/fbdv-simple.obo

with

https://raw.githubusercontent.com/FlyBase/drosophila-developmental-ontology/master/fbdv-simple.obo

I would like to warn that the [ROBOT diff](https://github.com/FlyBase/drosophila-developmental-ontology/blob/master/reports/robot_simple_diff.txt) looks big, but I think it is mostly the updated relation (part_of?). Maybe double check the new version uses the correct one!

**Comment by matentzn** [comment]
And make the this release ticket again when you are done. :) thanks

**Comment by Clare72** [comment]
The part_of changes are masked in the diff in Atom (as the ID is still part_of), so it is a bit less scary!
The new part_of has 'xref: FBdv:00018001' and 'name: substage of', is this the 'correct one'?

I am a bit concerned about all the typedef changes. There are a lot of 'property_value:' annotations coming in, two terms have multiple names and one term has multiple comments. I don't think these changes will be ok for FlyBase, so we might need to generate a FlyBase version (but perhaps we don't need to do this right now, since we aren't updating fbdv in FlyBase just yet).

There are also greeks in the definition of preceded_by. We are thinking about trying to put greeks into fbbt and it seems like it should not be a big problem, but it is still as yet untested...

The file also fails to load in oboedit because of the line 'subset: ro-eco' in a few of the typedefs (this subset is not defined). It would be good to produce an oboedit-compatible file.

**Comment by matentzn** [comment]
Perfect, thank you!

> The new part_of has 'xref: FBdv:00018001' and 'name: substage of', is this the 'correct one'?

@dosumis (we have been over this a few times, but better save than sorry)

> There are a lot of 'property_value:' annotations coming in

Not too concerning. This is normal as we are pulling in all annotations from external ontologies!

> , two terms have multiple names and one term has multiple comments

Will fix.

> we might need to generate a FlyBase version;
Sure! Do you want to model this after the flybase-fbcv version?

> There are also greeks in the definition.
I am not worried about greeks. They are good people usually, and in case of an encoding failure, they are happy to latinize their names.

> subset: ro-eco
Is a bug, will make ticket

**Comment by Clare72** [comment]
For FlyBase:
The previous file didn't have any 'property_value:'s, so probably best to just strip all these out.
Any 'xref: OBO_REL:'s were previously changed manually to 'xref_analog: OBO_REL:'
We might need to remove 'namespace: external' from has_part (and possibly any namespaces that are not 'relationship' from all typedefs if any of these appear in the future)
We may need to add 'namespace: relationship' to part_of and preceded_by, but it is not needed for immediately_preceded_by, so I am not 100% convinced it is necessary.

The FlyBase version will definitely need to open in oboedit (curators use it).

**Comment by matentzn** [comment]
@Clare72 when you have time (zero pressure now), can you break out each individual item here into a seperate ticket? Merci!

**Comment by Clare72** [comment]
all fine now
