### ISSUE TITLE
question about last release of fbdv-full.obo

### ISSUE THREAD

**Issue by ANiknejad** [FlyBase/drosophila-developmental-ontology#88]
Hello Damien @gouttegd 

in https://github.com/FlyBase/drosophila-developmental-ontology/releases/download/v2023-12-07/fbdv-full.obo
released '4 days ago', I am wondering about

> [Term]
> id: FBdv:00007022
> name: embryonic cycle interphase
> def: "The interphase (GO:0051325) of an embryonic cycle." [FBC:DOS]
> is_a: FBdv:00007024 ! biological process
> is_a: GO:0051329 ! mitotic interphase
> intersection_of: GO:0051325 ! interphase
> intersection_of: FBdv:00018001 FBdv:00007011 ! substage of embryonic cycle
> relationship: FBdv:00018001 FBdv:00007011 ! substage of embryonic cycle
> 

and 

> [Typedef]
> id: FBdv:00018001
> name: substage of
> namespace: relationship
> def: "A relation between a developmental stage and another, larger developmental stage during which it happens." [FBC:DPG]
> comment: Creating this relation as a temporar> [Typedef]
> id: FBdv:00018001
> name: substage of
> namespace: relationship
> def: "A relation between a developmental stage and another, larger developmental stage during which it happens." [FBC:DPG]
> comment: Creating this relation as a **temporary fix**, pending adding the axiom occurrent_part_of subproperty of happens_during to RO.
> is_transitive: true
> is_a: RO:0002012 ! occurrent part of
> is_a: RO:0002092 ! happens duringy fix, pending adding the axiom occurrent_part_of subproperty of happens_during to RO.
> is_transitive: true
> is_a: RO:0002012 ! occurrent part of
> is_a: RO:0002092 ! happens during

Is there a refinement of the relationships into FBdv scheduled?
I am asking because currently in charge of building new developmental ontologies for various arthropods species, I am looking to following as much as possible the FBdv ontology rules.

Many thanks in advance for any explanation.
Best regards,

Anne

**Comment by gouttegd** [comment]
Hello Anne,

> Is there a refinement of the relationships into FBdv scheduled?

No. And the “temporary fix” mentioned in FBdv:00018001 (which has been there for quite a while, by the way: it’s not a new thing from the last release) is likely to become a permanent fix, because the OBO Relation Ontology is seemingly no longer considering making `occurrent_part_of` a subproperty of `happens_during`. In fact, they are considering **obsoleting** `occurent_part_of` (https://github.com/oborel/obo-relations/issues/518), and to promote the use of `part_of` instead to express temporal partonomy relationships – something that we can’t do in FBdv because we use those relationships in DPO to automatically classify lethal phenotypes.

**Comment by ANiknejad** [comment]
Thank you very much for your explanations, Damien!

**Comment by Clare72** [comment]
closing this as nothing further to do
